language: scala
sudo: true
scala:
   - 2.11.7
env:
  global:
    - Z3_URL=https://github.com/Z3Prover/z3/releases/download/z3-4.5.0/z3-4.5.0-x64-ubuntu-14.04.zip
    - BOOGIE_URL=https://github.com/boogie-org/boogie/archive/63de8b442914a044223d546eb4c2a1db003ada6d.zip
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get install nuget
  - sudo apt-get install mono-devel
install:
  - wget -O z3.zip ${Z3_URL}
  - wget -O boogie.zip ${BOOGIE_URL}
  - unzip z3.zip
  - unzip boogie.zip
  - export Z3_HOME=$(ls -d z3*/)
  - export BOOGIE_HOME=$(ls -d boogie*/)
  - nuget restore ${BOOGIE_HOME}/Source/Boogie.sln
  - msbuild ${BOOGIE_HOME}/Source/Boogie.sln
  - ln -s ${PWD}/${Z3_HOME}/bin/z3 ${BOOGIE_HOME}/Binaries/z3.exe
  - printf -v BOOGIE_SCRIPT '#!/bin/bash\nmono $BOOGIE_HOME/Binaries/Boogie.exe $@'
  - echo "$BOOGIE_SCRIPT" > boogie
  - chmod 744 boogie
  - export PATH=.:$PATH
